random_state: 42
test_size: 0.2
batch_size: 32
weight_decay: 0.01
dropout_rate: 0.3
max_epochs: 100
patience: 15
learning_rate: 0.0001
scheduler:
  min_lr: 0.00001
  patience: 15
  factor: 0.5
weight_path: resources/model.pt
clean_file_path: resources/clean.csv