random_state: 42
test_size: 0.2
batch_size: 64
weight_decay: 0.01
dropout_rate: 0.3
max_epochs: 20
patience: 20
learning_rate: 0.00003
scheduler:
  min_lr: 0.00001
  patience: 15
  factor: 0.5
train_data: resources/data.csv
test_data: resources/test.csv
weight_path: resources/model.pt
clean_train: resources/clean_train.csv
clean_test: resources/clean_test.csv